image:
  repository: fadidasus/order-sys
  tag: "landing-page-9944448"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi

service:
  port: 8080

ingress:
  hosts:
    - test.syrianorder.com
  tlsSecret: landing-page-tls
  clusterIssuer: letsencrypt-prod
